### PR TITLE
bluebird promises

### PR DESCRIPTION
**Pull request by rom1504**
the style is ok too, more functional, and it's faster

### CODE REVIEW

**Comment by rom1504** [comment]
Well 5s vs 6s with async/await in circle ci. It's not a lot, it seems the perf problem isn't quite that

**Comment by rom1504** [comment]
I guess I should just try to profile it....

**Comment by rom1504** [comment]
6433 ticks for async/await, 3963 for promises

**Comment by rom1504** [comment]
`globals.Promise = require('bluebird');`

**Comment by rom1504** [comment]
I forgot an async in numeric, fixing that improved by at least 25%.
using bluebird divides the time by 2.

still 3 times master time, but it's getting reasonable.

**Comment by rom1504** [comment]
in circle ci, we're at 3s (instead of 6s for babel default async/await )
without bluebird yet, trying to find how to use it (without putting `var _promise = require('bluebird');` manually in dist/ files)

**Comment by rom1504** [comment]
down to 1s with bluebird

**Comment by rom1504** [comment]
tried it with 100k iterations as in master : 13s
master does 1.7s

it's more reasonable that way, but it's still pretty slow compared to the sync solution (master)

**Comment by rom1504** [comment]
ohhh actually, using the exact same benchmark script (using the stream for reading) give me 12s for reading.
So that means there is some overhead for using the stream and events, but that's ok.

So these 13s are a decent score. It might be possible to get the same score with async/await.

We might prefer a pure promise implementation vs async/await though.

**Comment by roblabla** [comment]
Well async/await and promises are pretty much "compatible" so I guess whatever we do is OK.

**Comment by rom1504** [comment]
@roblabla you'd think so but not if we want to use bluebird.
Only way to use bluebird with babel5 is disabling the runtime and do `global.Promise=require('bluebird')`

(Yes I tried, `require('babel-runtime/core-js/promise').default = require('bluebird');` doesn't work)

that's just internally though, external users can use whatever.

**Comment by roblabla** [comment]
I'm not sure I understand. Why would you want the global Promise to be bluebird ? Babel has its own Pormise polyfill, and nodejs comes with a promise impl built-in nowadays.

**Comment by rom1504** [comment]
Because bluebird is twice as fast than both (all implemented in js), see  https://github.com/roblabla/ProtoDef/pull/37#issuecomment-161850219

**Comment by rom1504** [comment]
(we could probably do var Promise=require('bluebird') instead of using the global though)

**Comment by rom1504** [comment]
closing in favor of #43

**Pull request closed without merging**
