### PR TITLE
add serializer (generalize from nmp), progress on #11

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
I guess it might still be a little bit nmp specific, since I assume an id and all ?

**Comment by rom1504** [comment]
To use this it nmp, it's mostly needed to create 1 serializer/parser by state and change the serializer/parser when changing of state. (also give the right packets to the serializer/parser depending on toServer)

**Comment by rom1504** [comment]
what exactly is mc-specific here ? the packet structure ? how can we make this more general ? (defining the packet structure as a type ?)

**Comment by rom1504** [comment]
used in https://github.com/PrismarineJS/node-minecraft-protocol/pull/274

I think most of the work is done here. Making it less mc-specific shouldn't change much.

**Comment by rom1504** [comment]
Currently without packetToParse, should be put in switch somehow.
Error handling is not needed anymore in the serializer since it's all done in container.

**Comment by rom1504** [comment]
Alright one problem here is we are losing the type name (=packet name) information. I think a way to go around that would be to keep the information of the type found when reading a switch.

**Comment by rom1504** [comment]
I added the type information to metadata.

**Comment by rom1504** [comment]
Working and usable by nmp. Main problem is ProtoDef class appears to be slow (might be related to the getField function we call too much)

**Comment by rom1504** [comment]
Good enough imho.
(I don't know how to integrate packetToParse cleanly but I'm not sure if we really need it (?))

**Comment by roblabla** [comment]
We'll need it down the road probably, as it helps quite a lot in performance, but in the meantime we can just forget about it.

**Comment by rom1504** [comment]
@roblabla can you take a look at this PR ? I think it's ready and it would be better to get nmp to use this before too long, so we don't have to move changes from nmp to protodef again.

**Pull request merged**
